
version: '3'
services:
    mongod:
        image: mongo
        ports:
            - '27017:27017'
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongod
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
        depends_on:
            - mongod
        ports:
          - "8080:8081"
    banking-app-node:
        build: ./banking-app-node
        ports:
            - '3000:3000'
        environment:
            DB_CONNECTION: mongodb://mongod:27017
        depends_on:
            - mongod
        stdin_open: true
        tty: true
        restart: always
    banking-app-react:
        build: ./banking-app-react
        ports:
            - '5173:5173'
        stdin_open: true
        tty: true